"use server";

import type { JobCard, JobCardLineItem, JobCardStatus } from "../models/JobCard";
import { getJobLineItems, getJobBayId, normalizeJobStatus } from "../models/JobCard";
import type { Customer } from "../models/Customer";
import type { Vehicle } from "../models/Vehicle";
import { assertNoError, firstOrNull } from "../database/helpers";
import {
  customerFromRow,
  jobFromRow,
  jobToRow,
  vehicleFromRow,
  vehicleToRow,
  type CustomerRow,
  type JobRow,
  type VehicleRow,
} from "../database/mappers";
import { generateId } from "../generateId";
import { supabase } from "../supabase";
import { simulateLatency } from "./delay";
import { getBayById, setBayStatus } from "./bay_repository";

/**
 * A JobCard with its related Customer and Vehicle records joined in.
 * Either relation may be null if the referenced row no longer exists.
 */
export interface JobCardWithRelations extends JobCard {
  customer: Customer | null;
  vehicle: Vehicle | null;
}

/**
 * Payload accepted by createJobCard. The id and audit timestamps are
 * generated by the repository, so callers must not supply them.
 */
export type CreateJobCardInput = Omit<
  JobCard,
  "id" | "created_at" | "updated_at"
> & {
  status?: JobCardStatus;
};

async function deductInventoryForLineItems(
  _lineItems: JobCardLineItem[],
): Promise<void> {
  return;
}

function shouldDeductInventory(
  previousStatus: JobCardStatus,
  nextStatus: JobCardStatus,
): boolean {
  return (
    previousStatus === "Estimate" &&
    (nextStatus === "Approved" || nextStatus === "In Progress")
  );
}

function normalizeJobRecord(job: JobCard): JobCard {
  return {
    ...job,
    technicianId: job.technicianId ?? job.assigned_technician_id ?? null,
    bayId: job.bayId ?? null,
    created_by: job.created_by,
    created_at: job.created_at,
    updated_at: job.updated_at,
    line_items: job.line_items ?? [],
    queue_index: job.queue_index,
  };
}

async function fetchJobs(): Promise<JobCard[]> {
  const result = await supabase.from("jobs").select("*");
  const rows = assertNoError(result, "fetchJobs") as JobRow[];
  return (rows ?? []).map((row) => normalizeJobRecord(jobFromRow(row)));
}

async function releaseBay(bayId: string | null | undefined, excludeJobId?: string): Promise<void> {
  if (!bayId) return;
  const bay = await getBayById(bayId);
  if (bay && bay.status === "Occupied") {
    const result = await supabase.from("jobs").select("*").eq("bay_id", bayId);
    const jobs = (assertNoError(result, "releaseBay") as JobRow[]).map((row) => jobFromRow(row));
    const queuedJobs = jobs.filter(
      (job) =>
        job.id !== excludeJobId &&
        (normalizeJobStatus(job.status) === "In Progress" ||
          normalizeJobStatus(job.status) === "Approved"),
    );
    if (queuedJobs.length === 0) {
      await setBayStatus(bayId, "Open");
    }
  }
}

async function occupyBay(bayId: string): Promise<void> {
  const bay = await getBayById(bayId);
  if (!bay) {
    throw new Error("Selected bay was not found.");
  }
  if (bay.status === "Maintenance") {
    throw new Error(`Bay "${bay.name}" is currently under maintenance.`);
  }
  if (bay.status !== "Occupied") {
    await setBayStatus(bayId, "Occupied");
  }
}

async function joinJobRelations(jobCard: JobCard): Promise<JobCardWithRelations> {
  const [customerResult, vehicleResult] = await Promise.all([
    supabase.from("customers").select("*").eq("id", jobCard.customer_id).limit(1),
    supabase.from("vehicles").select("*").eq("id", jobCard.vehicle_id).limit(1),
  ]);

  const customerRow = firstOrNull(assertNoError(customerResult, "joinJobRelations") as CustomerRow[]);
  const vehicleRow = firstOrNull(assertNoError(vehicleResult, "joinJobRelations") as VehicleRow[]);

  return {
    ...jobCard,
    customer: customerRow ? customerFromRow(customerRow) : null,
    vehicle: vehicleRow ? vehicleFromRow(vehicleRow) : null,
  };
}

/**
 * Returns all job cards.
 */
export async function getJobCards(): Promise<JobCard[]> {
  await simulateLatency();
  return fetchJobs();
}

/**
 * Returns every job card belonging to a given customer, newest first.
 * Used by the CRM profile to render a customer's service history.
 */
export async function getJobCardsByCustomerId(
  customerId: string,
): Promise<JobCard[]> {
  await simulateLatency();
  const result = await supabase
    .from("jobs")
    .select("*")
    .eq("customer_id", customerId)
    .order("created_at", { ascending: false });
  const rows = assertNoError(result, "getJobCardsByCustomerId") as JobRow[];
  return (rows ?? []).map((row) => normalizeJobRecord(jobFromRow(row)));
}

/**
 * Returns a single job card by id with its Customer and Vehicle joined in,
 * or null if no job card matches.
 */
export async function getJobCardById(
  id: string,
): Promise<JobCardWithRelations | null> {
  await simulateLatency();

  const result = await supabase.from("jobs").select("*").eq("id", id).limit(1);
  const row = firstOrNull(assertNoError(result, "getJobCardById") as JobRow[]);
  if (!row) return null;

  return joinJobRelations(normalizeJobRecord(jobFromRow(row)));
}

/**
 * Returns all job cards with their Customer and Vehicle joined in.
 */
export async function getRecentJobsWithRelations(): Promise<JobCardWithRelations[]> {
  await simulateLatency();
  const jobs = await fetchJobs();

  const customerIds = [...new Set(jobs.map((job) => job.customer_id))];
  const vehicleIds = [...new Set(jobs.map((job) => job.vehicle_id))];

  const [customersResult, vehiclesResult] = await Promise.all([
    customerIds.length
      ? supabase.from("customers").select("*").in("id", customerIds)
      : Promise.resolve({ data: [], error: null }),
    vehicleIds.length
      ? supabase.from("vehicles").select("*").in("id", vehicleIds)
      : Promise.resolve({ data: [], error: null }),
  ]);

  const customers = new Map(
    ((assertNoError(customersResult, "getRecentJobsWithRelations") as CustomerRow[]) ?? []).map(
      (row) => [row.id, customerFromRow(row)],
    ),
  );
  const vehicles = new Map(
    ((assertNoError(vehiclesResult, "getRecentJobsWithRelations") as VehicleRow[]) ?? []).map(
      (row) => [row.id, vehicleFromRow(row)],
    ),
  );

  return jobs
    .map((job) => ({
      ...job,
      customer: customers.get(job.customer_id) ?? null,
      vehicle: vehicles.get(job.vehicle_id) ?? null,
    }))
    .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
}

/**
 * Creates a new job card and returns the persisted record.
 *
 * Security: the `created_by` field (referencing the acting User.id) is
 * mandatory for the audit trail. Creation is rejected when it is missing,
 * empty, or not a string.
 */
export async function createJobCard(
  data: CreateJobCardInput,
): Promise<JobCard> {
  if (
    !data ||
    typeof data.created_by !== "string" ||
    data.created_by.trim() === ""
  ) {
    throw new Error(
      "createJobCard: `created_by` is required for the security audit trail and cannot be empty.",
    );
  }

  await simulateLatency();

  const now = new Date().toISOString();
  const jobCard: JobCard = {
    ...data,
    status: data.status ?? "Estimate",
    technicianId: data.technicianId ?? data.assigned_technician_id ?? null,
    bayId: data.bayId ?? null,
    line_items: data.line_items ?? [],
    id: generateId(),
    created_at: now,
    updated_at: now,
  };

  const result = await supabase
    .from("jobs")
    .insert(jobToRow(jobCard))
    .select("*")
    .single();
  const created = normalizeJobRecord(jobFromRow(assertNoError(result, "createJobCard") as JobRow));

  if (created.status === "Approved" || created.status === "In Progress") {
    await deductInventoryForLineItems(getJobLineItems(created));
  }

  if (created.status === "In Progress" && created.bayId) {
    await occupyBay(created.bayId);
  }

  return created;
}

/**
 * Updates a job card's status and calculates next service date if completed/invoiced.
 */
export async function updateJobStatus(
  jobId: string,
  newStatus: JobCardStatus,
): Promise<JobCardWithRelations | null> {
  await simulateLatency();

  const existingResult = await supabase.from("jobs").select("*").eq("id", jobId).limit(1).single();
  const existingRow = assertNoError(existingResult, "updateJobStatus") as JobRow;
  if (!existingRow) return null;

  const jobCard = normalizeJobRecord(jobFromRow(existingRow));
  const previousStatus = normalizeJobStatus(jobCard.status);

  if (shouldDeductInventory(previousStatus, newStatus)) {
    await deductInventoryForLineItems(getJobLineItems(jobCard));
  }

  if (newStatus === "In Progress") {
    const bayId = getJobBayId(jobCard);
    if (!bayId) {
      throw new Error(
        "A bay must be assigned before starting work on this job.",
      );
    }
    await occupyBay(bayId);
  }

  if (newStatus === "Completed") {
    await releaseBay(getJobBayId(jobCard), jobId);
  }

  jobCard.status = newStatus;
  jobCard.updated_at = new Date().toISOString();

  let vehicle: Vehicle | null = null;
  if (newStatus === "Completed") {
    const vehicleResult = await supabase
      .from("vehicles")
      .select("*")
      .eq("id", jobCard.vehicle_id)
      .limit(1)
      .single();
    const vehicleRow = assertNoError(vehicleResult, "updateJobStatus") as VehicleRow;
    if (vehicleRow) {
      const nextServiceDate = new Date();
      nextServiceDate.setDate(nextServiceDate.getDate() + 180);
      vehicle = {
        ...vehicleFromRow(vehicleRow),
        next_service_date: nextServiceDate.toISOString(),
      };
      const updateVehicleResult = await supabase
        .from("vehicles")
        .update(vehicleToRow(vehicle))
        .eq("id", vehicle.id);
      assertNoError(updateVehicleResult, "updateJobStatus");
    }
  } else {
    const vehicleResult = await supabase
      .from("vehicles")
      .select("*")
      .eq("id", jobCard.vehicle_id)
      .limit(1);
    const vehicleRow = firstOrNull(assertNoError(vehicleResult, "updateJobStatus") as VehicleRow[]);
    vehicle = vehicleRow ? vehicleFromRow(vehicleRow) : null;
  }

  const updateResult = await supabase
    .from("jobs")
    .update(jobToRow(jobCard))
    .eq("id", jobId)
    .select("*")
    .single();
  const updatedJob = normalizeJobRecord(jobFromRow(assertNoError(updateResult, "updateJobStatus") as JobRow));

  const customerResult = await supabase
    .from("customers")
    .select("*")
    .eq("id", updatedJob.customer_id)
    .limit(1);
  const customerRow = firstOrNull(assertNoError(customerResult, "updateJobStatus") as CustomerRow[]);

  return {
    ...updatedJob,
    customer: customerRow ? customerFromRow(customerRow) : null,
    vehicle,
  };
}

export interface UpdateJobAssignmentsInput {
  technicianId?: string | null;
  bayId?: string | null;
}

/**
 * Updates technician and/or bay assignment for a job card.
 * If the job is already in progress, bay changes release the old bay and
 * occupy the newly selected open bay.
 */
export async function updateJobAssignments(
  jobId: string,
  data: UpdateJobAssignmentsInput,
): Promise<JobCardWithRelations | null> {
  await simulateLatency();

  const existingResult = await supabase.from("jobs").select("*").eq("id", jobId).limit(1).single();
  const existingRow = assertNoError(existingResult, "updateJobAssignments") as JobRow;
  if (!existingRow) return null;

  const jobCard = normalizeJobRecord(jobFromRow(existingRow));
  const previousBayId = getJobBayId(jobCard);
  const isInProgress = normalizeJobStatus(jobCard.status) === "In Progress";

  if (data.technicianId !== undefined) {
    jobCard.technicianId = data.technicianId;
    if (data.technicianId) {
      jobCard.assigned_technician_id = data.technicianId;
    }
  }

  if (data.bayId !== undefined) {
    if (data.bayId && isInProgress) {
      if (previousBayId && previousBayId !== data.bayId) {
        await releaseBay(previousBayId, jobId);
      }
      await occupyBay(data.bayId);
    }
    jobCard.bayId = data.bayId;
  }

  jobCard.updated_at = new Date().toISOString();

  const updateResult = await supabase
    .from("jobs")
    .update(jobToRow(jobCard))
    .eq("id", jobId)
    .select("*")
    .single();
  const updatedJob = normalizeJobRecord(jobFromRow(assertNoError(updateResult, "updateJobAssignments") as JobRow));

  return joinJobRelations(updatedJob);
}

export interface AddJobLineItemInput {
  serviceId?: string;
  partId?: string;
  name: string;
  quantity: number;
  unitPrice: number;
  gst_rate?: number;
}

function recalculateJobTotals(lineItems: JobCardLineItem[]) {
  let subtotal = 0;
  let total_tax = 0;

  for (const item of lineItems) {
    const amount = item.quantity * item.unitPrice;
    const gstRate = item.gst_rate ?? 18;
    subtotal += amount;
    total_tax += (amount * gstRate) / 100;
  }

  return {
    subtotal,
    total_tax,
    total_amount: subtotal + total_tax,
  };
}

/**
 * Appends a service or part line item to an existing job card and
 * recalculates financial totals.
 */
export async function appendLineItemToJob(
  jobId: string,
  input: AddJobLineItemInput,
): Promise<JobCardWithRelations | null> {
  await simulateLatency();

  const existingResult = await supabase.from("jobs").select("*").eq("id", jobId).limit(1).single();
  const existingRow = assertNoError(existingResult, "appendLineItemToJob") as JobRow;
  if (!existingRow) return null;

  const jobCard = normalizeJobRecord(jobFromRow(existingRow));
  const quantity = input.quantity || 1;
  const unitPrice = input.unitPrice;
  const newLineItem: JobCardLineItem = {
    serviceId: input.serviceId,
    partId: input.partId,
    name: input.name,
    quantity,
    unitPrice,
    total: quantity * unitPrice,
    gst_rate: input.gst_rate ?? 18,
  };

  jobCard.line_items = [...getJobLineItems(jobCard), newLineItem];
  const totals = recalculateJobTotals(jobCard.line_items);
  jobCard.subtotal = totals.subtotal;
  jobCard.total_tax = totals.total_tax;
  jobCard.total_amount = totals.total_amount;
  jobCard.updated_at = new Date().toISOString();

  const updateResult = await supabase
    .from("jobs")
    .update(jobToRow(jobCard))
    .eq("id", jobId)
    .select("*")
    .single();
  const updatedJob = normalizeJobRecord(jobFromRow(assertNoError(updateResult, "appendLineItemToJob") as JobRow));

  return joinJobRelations(updatedJob);
}

export type Timeframe = "today" | "week" | "month" | "all";

function isWithinTimeframe(dateStr: string, timeframe: Timeframe): boolean {
  if (timeframe === "all") return true;

  const date = new Date(dateStr);
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());

  if (timeframe === "today") {
    const d = new Date(date.getFullYear(), date.getMonth(), date.getDate());
    return d.getTime() === today.getTime();
  }

  if (timeframe === "week") {
    const weekAgo = new Date(today);
    weekAgo.setDate(today.getDate() - 7);
    return date.getTime() >= weekAgo.getTime();
  }

  if (timeframe === "month") {
    const monthAgo = new Date(today);
    monthAgo.setMonth(today.getMonth() - 1);
    return date.getTime() >= monthAgo.getTime();
  }

  return true;
}

/**
 * Calculates key metrics for the dashboard.
 */
export async function getDashboardMetrics(timeframe: Timeframe = "today") {
  await simulateLatency();

  const jobs = await fetchJobs();

  let revenue = 0;
  let pendingJobs = 0;
  let completedJobs = 0;

  for (const job of jobs) {
    if (!isWithinTimeframe(job.created_at, timeframe) && !isWithinTimeframe(job.updated_at, timeframe)) {
      continue;
    }

    const status = normalizeJobStatus(job.status);

    if (
      status === "Estimate" ||
      status === "Approved" ||
      status === "In Progress"
    ) {
      pendingJobs++;
    } else if (status === "Completed" || status === "Closed") {
      completedJobs++;
      revenue += job.total_amount;
    }
  }

  return { revenue, pendingJobs, completedJobs };
}

export interface ServiceAnalytics {
  topByVolume: { name: string; volume: number }[];
  topByRevenue: { name: string; revenue: number }[];
  averageTicketSize: number;
}

/**
 * Calculates service performance metrics.
 */
export async function getServiceAnalytics(timeframe: Timeframe = "today"): Promise<ServiceAnalytics> {
  await simulateLatency();

  const jobs = await fetchJobs();

  const validJobs = jobs.filter(
    (job) => {
      const status = normalizeJobStatus(job.status);
      return (
        (status === "Completed" || status === "Closed") &&
        (isWithinTimeframe(job.created_at, timeframe) ||
          isWithinTimeframe(job.updated_at, timeframe))
      );
    },
  );

  let totalRevenue = 0;
  const volumeMap = new Map<string, number>();
  const revenueMap = new Map<string, number>();

  for (const job of validJobs) {
    totalRevenue += job.total_amount;

    const lineItems = getJobLineItems(job);

    if (lineItems.length > 0) {
      for (const item of lineItems) {
        const qty = item.quantity || 1;
        const rate = item.unitPrice || 0;

        volumeMap.set(item.name, (volumeMap.get(item.name) || 0) + qty);
        revenueMap.set(
          item.name,
          (revenueMap.get(item.name) || 0) + (item.total || rate * qty),
        );
      }
    }
  }

  const topByVolume = Array.from(volumeMap.entries())
    .map(([name, volume]) => ({ name, volume }))
    .sort((a, b) => b.volume - a.volume)
    .slice(0, 5);

  const topByRevenue = Array.from(revenueMap.entries())
    .map(([name, revenue]) => ({ name, revenue }))
    .sort((a, b) => b.revenue - a.revenue)
    .slice(0, 5);

  const averageTicketSize =
    validJobs.length > 0 ? totalRevenue / validJobs.length : 0;

  return {
    topByVolume,
    topByRevenue,
    averageTicketSize,
  };
}

export interface RevenueTrendData {
  name: string;
  revenue: number;
}

export async function getRevenueTrend(timeframe: Timeframe = "week"): Promise<RevenueTrendData[]> {
  await simulateLatency();
  const jobs = await fetchJobs();

  const validJobs = jobs.filter(
    (job) => {
      const status = normalizeJobStatus(job.status);
      return (
        (status === "Completed" || status === "Closed") &&
        (isWithinTimeframe(job.created_at, timeframe) ||
          isWithinTimeframe(job.updated_at, timeframe))
      );
    },
  );

  const buckets: { [key: string]: number } = {};
  const now = new Date();

  if (timeframe === "today") {
    for (let i = 0; i <= now.getHours(); i++) {
      const d = new Date(now.getFullYear(), now.getMonth(), now.getDate(), i, 0, 0);
      buckets[d.toLocaleTimeString("en-US", { hour: "numeric", hour12: true })] = 0;
    }
  } else if (timeframe === "week") {
    for (let i = 6; i >= 0; i--) {
      const d = new Date(now.getFullYear(), now.getMonth(), now.getDate() - i);
      buckets[d.toLocaleDateString("en-US", { weekday: "short" })] = 0;
    }
  } else if (timeframe === "month") {
    for (let i = 29; i >= 0; i--) {
      const d = new Date(now.getFullYear(), now.getMonth(), now.getDate() - i);
      buckets[d.toLocaleDateString("en-US", { month: "short", day: "numeric" })] = 0;
    }
  } else if (timeframe === "all") {
    for (let i = 11; i >= 0; i--) {
      const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
      buckets[d.toLocaleDateString("en-US", { month: "short", year: "2-digit" })] = 0;
    }
  }

  for (const job of validJobs) {
    const date = new Date(job.created_at);
    let key = "";
    if (timeframe === "today") {
      key = date.toLocaleTimeString("en-US", { hour: "numeric", hour12: true });
    } else if (timeframe === "week") {
      key = date.toLocaleDateString("en-US", { weekday: "short" });
    } else if (timeframe === "month") {
      key = date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
    } else if (timeframe === "all") {
      key = date.toLocaleDateString("en-US", { month: "short", year: "2-digit" });
    }

    if (buckets[key] !== undefined) {
      buckets[key] += job.total_amount;
    } else {
      buckets[key] = job.total_amount;
    }
  }

  return Object.entries(buckets).map(([name, revenue]) => ({ name, revenue }));
}

/**
 * Updates the queue order for a list of job IDs.
 */
export async function updateJobQueueOrder(jobIds: string[]): Promise<void> {
  await simulateLatency();

  const now = new Date().toISOString();
  await Promise.all(
    jobIds.map(async (id, index) => {
      const result = await supabase
        .from("jobs")
        .update({ queue_index: index, updated_at: now })
        .eq("id", id)
        .neq("queue_index", index);
      assertNoError(result, "updateJobQueueOrder");
    }),
  );
}
