"use server";

import type { JobCard } from "../models/JobCard";
import type { Customer } from "../models/Customer";
import type { Vehicle } from "../models/Vehicle";
import { readData, writeData } from "../db";
import { generateId } from "../generateId";
import { simulateLatency } from "./delay";

const FILE_NAME = "jobs.json";
const CUSTOMERS_FILE = "customers.json";
const VEHICLES_FILE = "vehicles.json";

/**
 * A JobCard with its related Customer and Vehicle records joined in.
 * Either relation may be null if the referenced row no longer exists.
 */
export interface JobCardWithRelations extends JobCard {
  customer: Customer | null;
  vehicle: Vehicle | null;
}

/**
 * Payload accepted by createJobCard. The id and audit timestamps are
 * generated by the repository, so callers must not supply them.
 */
export type CreateJobCardInput = Omit<
  JobCard,
  "id" | "created_at" | "updated_at"
>;

/**
 * Returns all job cards.
 */
export async function getJobCards(): Promise<JobCard[]> {
  await simulateLatency();
  return readData<JobCard[]>(FILE_NAME);
}

/**
 * Returns every job card belonging to a given customer, newest first.
 * Used by the CRM profile to render a customer's service history.
 */
export async function getJobCardsByCustomerId(
  customerId: string,
): Promise<JobCard[]> {
  await simulateLatency();
  const jobs = await readData<JobCard[]>(FILE_NAME);
  return jobs
    .filter((job) => job.customer_id === customerId)
    .sort(
      (a, b) =>
        new Date(b.created_at).getTime() - new Date(a.created_at).getTime(),
    );
}

/**
 * Returns a single job card by id with its Customer and Vehicle joined in,
 * or null if no job card matches.
 */
export async function getJobCardById(
  id: string,
): Promise<JobCardWithRelations | null> {
  await simulateLatency();

  const jobs = await readData<JobCard[]>(FILE_NAME);
  const jobCard = jobs.find((job) => job.id === id);
  if (!jobCard) return null;

  const customers = await readData<Customer[]>(CUSTOMERS_FILE);
  const vehicles = await readData<Vehicle[]>(VEHICLES_FILE);

  const customer = customers.find((c) => c.id === jobCard.customer_id) ?? null;
  const vehicle = vehicles.find((v) => v.id === jobCard.vehicle_id) ?? null;

  return { ...jobCard, customer, vehicle };
}

/**
 * Creates a new job card and returns the persisted record.
 *
 * Security: the `created_by` field (referencing the acting User.id) is
 * mandatory for the audit trail. Creation is rejected when it is missing,
 * empty, or not a string.
 */
export async function createJobCard(
  data: CreateJobCardInput,
): Promise<JobCard> {
  if (
    !data ||
    typeof data.created_by !== "string" ||
    data.created_by.trim() === ""
  ) {
    throw new Error(
      "createJobCard: `created_by` is required for the security audit trail and cannot be empty.",
    );
  }

  await simulateLatency();

  const now = new Date().toISOString();
  const jobCard: JobCard = {
    ...data,
    id: generateId(),
    created_at: now,
    updated_at: now,
  };

  const jobs = await readData<JobCard[]>(FILE_NAME);
  jobs.push(jobCard);
  await writeData(FILE_NAME, jobs);

  return jobCard;
}

/**
 * Updates a job card's status and calculates next service date if completed/invoiced.
 */
export async function updateJobStatus(
  jobId: string,
  newStatus: string,
): Promise<JobCardWithRelations | null> {
  await simulateLatency();

  const jobs = await readData<JobCard[]>(FILE_NAME);
  const jobIndex = jobs.findIndex((job) => job.id === jobId);
  if (jobIndex === -1) return null;

  const jobCard = jobs[jobIndex];
  jobCard.status = newStatus as any;
  jobCard.updated_at = new Date().toISOString();

  const vehicles = await readData<Vehicle[]>(VEHICLES_FILE);
  const vehicleIndex = vehicles.findIndex((v) => v.id === jobCard.vehicle_id);
  
  // Smart Service Interval Calculation
  if (newStatus === "Completed" || newStatus === "Invoiced") {
    if (vehicleIndex !== -1) {
      const vehicle = vehicles[vehicleIndex];
      const nextServiceDate = new Date();
      nextServiceDate.setDate(nextServiceDate.getDate() + 180);
      vehicle.next_service_date = nextServiceDate.toISOString();
      await writeData(VEHICLES_FILE, vehicles);
    }
  }

  await writeData(FILE_NAME, jobs);

  const customers = await readData<Customer[]>(CUSTOMERS_FILE);
  const customer = customers.find((c) => c.id === jobCard.customer_id) ?? null;
  const vehicle = vehicleIndex !== -1 ? vehicles[vehicleIndex] : null;

  return { ...jobCard, customer, vehicle };
  return { ...jobCard, customer, vehicle };
}

export type Timeframe = "today" | "week" | "month" | "all";

function isWithinTimeframe(dateStr: string, timeframe: Timeframe): boolean {
  if (timeframe === "all") return true;

  const date = new Date(dateStr);
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());

  if (timeframe === "today") {
    const d = new Date(date.getFullYear(), date.getMonth(), date.getDate());
    return d.getTime() === today.getTime();
  }

  if (timeframe === "week") {
    const weekAgo = new Date(today);
    weekAgo.setDate(today.getDate() - 7);
    return date.getTime() >= weekAgo.getTime();
  }

  if (timeframe === "month") {
    const monthAgo = new Date(today);
    monthAgo.setMonth(today.getMonth() - 1);
    return date.getTime() >= monthAgo.getTime();
  }

  return true;
}

/**
 * Calculates key metrics for the dashboard.
 */
export async function getDashboardMetrics(timeframe: Timeframe = "today") {
  await simulateLatency();

  const jobs = await readData<JobCard[]>(FILE_NAME);

  let revenue = 0;
  let pendingJobs = 0;
  let completedJobs = 0;

  for (const job of jobs) {
    if (!isWithinTimeframe(job.created_at, timeframe) && !isWithinTimeframe(job.updated_at, timeframe)) {
      continue;
    }

    if (job.status === "Draft" || job.status === "In Progress") {
      pendingJobs++;
    } else if (job.status === "Completed" || job.status === "Invoiced") {
      completedJobs++;
      if (job.status === "Invoiced") {
        revenue += job.total_amount;
      }
    }
  }

  return { revenue, pendingJobs, completedJobs };
}

export interface ServiceAnalytics {
  topByVolume: { name: string; volume: number }[];
  topByRevenue: { name: string; revenue: number }[];
  averageTicketSize: number;
}

/**
 * Calculates service performance metrics.
 */
export async function getServiceAnalytics(timeframe: Timeframe = "today"): Promise<ServiceAnalytics> {
  await simulateLatency();

  const jobs = await readData<JobCard[]>(FILE_NAME);
  // Also load services in case we need to fallback for older jobs
  const servicesData = await readData<any[]>("services.json");
  const serviceMap = new Map(servicesData.map((s) => [s.id, s]));

  const validJobs = jobs.filter(
    (job) =>
      (job.status === "Completed" || job.status === "Invoiced") &&
      (isWithinTimeframe(job.created_at, timeframe) ||
        isWithinTimeframe(job.updated_at, timeframe))
  );

  let totalRevenue = 0;
  const volumeMap = new Map<string, number>();
  const revenueMap = new Map<string, number>();

  for (const job of validJobs) {
    totalRevenue += job.total_amount;

    if (job.service_items && job.service_items.length > 0) {
      // New format with full details
      for (const item of job.service_items) {
        const qty = item.qty || 1;
        const rate = item.rate || 0;

        volumeMap.set(item.name, (volumeMap.get(item.name) || 0) + qty);
        revenueMap.set(item.name, (revenueMap.get(item.name) || 0) + rate * qty);
      }
    } else if (job.service_item_ids && job.service_item_ids.length > 0) {
      // Old format fallback: assume qty=1 and lookup rate
      for (const serviceId of job.service_item_ids) {
        const service = serviceMap.get(serviceId);
        if (service) {
          volumeMap.set(service.name, (volumeMap.get(service.name) || 0) + 1);
          revenueMap.set(
            service.name,
            (revenueMap.get(service.name) || 0) + (service.price || 0)
          );
        }
      }
    }
  }

  const topByVolume = Array.from(volumeMap.entries())
    .map(([name, volume]) => ({ name, volume }))
    .sort((a, b) => b.volume - a.volume)
    .slice(0, 5);

  const topByRevenue = Array.from(revenueMap.entries())
    .map(([name, revenue]) => ({ name, revenue }))
    .sort((a, b) => b.revenue - a.revenue)
    .slice(0, 5);

  const averageTicketSize =
    validJobs.length > 0 ? totalRevenue / validJobs.length : 0;

  return {
    topByVolume,
    topByRevenue,
    averageTicketSize,
  };
}

export interface RevenueTrendData {
  name: string;
  revenue: number;
}

export async function getRevenueTrend(timeframe: Timeframe = "week"): Promise<RevenueTrendData[]> {
  await simulateLatency();
  const jobs = await readData<JobCard[]>(FILE_NAME);

  const validJobs = jobs.filter(
    (job) =>
      (job.status === "Invoiced" || job.status === "Completed") &&
      (isWithinTimeframe(job.created_at, timeframe) ||
        isWithinTimeframe(job.updated_at, timeframe))
  );

  const buckets: { [key: string]: number } = {};
  const now = new Date();

  if (timeframe === "today") {
    for (let i = 0; i <= now.getHours(); i++) {
      const d = new Date(now.getFullYear(), now.getMonth(), now.getDate(), i, 0, 0);
      buckets[d.toLocaleTimeString("en-US", { hour: "numeric", hour12: true })] = 0;
    }
  } else if (timeframe === "week") {
    for (let i = 6; i >= 0; i--) {
      const d = new Date(now.getFullYear(), now.getMonth(), now.getDate() - i);
      buckets[d.toLocaleDateString("en-US", { weekday: "short" })] = 0;
    }
  } else if (timeframe === "month") {
    for (let i = 29; i >= 0; i--) {
      const d = new Date(now.getFullYear(), now.getMonth(), now.getDate() - i);
      buckets[d.toLocaleDateString("en-US", { month: "short", day: "numeric" })] = 0;
    }
  } else if (timeframe === "all") {
    for (let i = 11; i >= 0; i--) {
      const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
      buckets[d.toLocaleDateString("en-US", { month: "short", year: "2-digit" })] = 0;
    }
  }

  for (const job of validJobs) {
    const date = new Date(job.created_at);
    let key = "";
    if (timeframe === "today") {
      key = date.toLocaleTimeString("en-US", { hour: "numeric", hour12: true });
    } else if (timeframe === "week") {
      key = date.toLocaleDateString("en-US", { weekday: "short" });
    } else if (timeframe === "month") {
      key = date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
    } else if (timeframe === "all") {
      key = date.toLocaleDateString("en-US", { month: "short", year: "2-digit" });
    }

    if (buckets[key] !== undefined) {
      buckets[key] += job.total_amount;
    } else {
      buckets[key] = job.total_amount;
    }
  }

  return Object.entries(buckets).map(([name, revenue]) => ({ name, revenue }));
}
