import type { JobCard } from "../models/JobCard";
import type { Customer } from "../models/Customer";
import type { Vehicle } from "../models/Vehicle";
import { mockJobCards, mockCustomers, mockVehicles } from "../mock_db";
import { simulateLatency } from "./delay";

/**
 * A JobCard with its related Customer and Vehicle records joined in.
 * Either relation may be null if the referenced row no longer exists.
 */
export interface JobCardWithRelations extends JobCard {
  customer: Customer | null;
  vehicle: Vehicle | null;
}

/**
 * Payload accepted by createJobCard. The id and audit timestamps are
 * generated by the repository, so callers must not supply them.
 */
export type CreateJobCardInput = Omit<
  JobCard,
  "id" | "created_at" | "updated_at"
>;

/**
 * Returns all job cards.
 */
export async function getJobCards(): Promise<JobCard[]> {
  await simulateLatency();
  return [...mockJobCards];
}

/**
 * Returns every job card belonging to a given customer, newest first.
 * Used by the CRM profile to render a customer's service history.
 */
export async function getJobCardsByCustomerId(
  customerId: string,
): Promise<JobCard[]> {
  await simulateLatency();
  return mockJobCards
    .filter((job) => job.customer_id === customerId)
    .sort(
      (a, b) =>
        new Date(b.created_at).getTime() - new Date(a.created_at).getTime(),
    );
}

/**
 * Returns a single job card by id with its Customer and Vehicle joined in,
 * or null if no job card matches.
 */
export async function getJobCardById(
  id: string,
): Promise<JobCardWithRelations | null> {
  await simulateLatency();

  const jobCard = mockJobCards.find((job) => job.id === id);
  if (!jobCard) return null;

  const customer =
    mockCustomers.find((c) => c.id === jobCard.customer_id) ?? null;
  const vehicle = mockVehicles.find((v) => v.id === jobCard.vehicle_id) ?? null;

  return { ...jobCard, customer, vehicle };
}

/**
 * Simulates creating a new job card and returns the persisted record.
 *
 * Security: the `created_by` field (referencing the acting User.id) is
 * mandatory for the audit trail. Creation is rejected when it is missing,
 * empty, or not a string.
 */
export async function createJobCard(
  data: CreateJobCardInput,
): Promise<JobCard> {
  if (
    !data ||
    typeof data.created_by !== "string" ||
    data.created_by.trim() === ""
  ) {
    throw new Error(
      "createJobCard: `created_by` is required for the security audit trail and cannot be empty.",
    );
  }

  await simulateLatency();

  const now = new Date().toISOString();
  const jobCard: JobCard = {
    ...data,
    id: crypto.randomUUID(),
    created_at: now,
    updated_at: now,
  };

  mockJobCards.push(jobCard);
  return jobCard;
}
